spring:
  application:
    name: bricool
  datasource:
    name: bricool
    url: jdbc:postgresql://localhost:5432/bricool
    username: postgres
    password: azerty123
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  web:
    path-match:
      matching-strategy: ant_path_matcher
    servlet:
      path: /api/v1



application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
